cc_library(
        name = "localsearchsolver",
        hdrs = [
                "iterated_local_search.hpp",
                "best_first_local_search.hpp",
                "genetic_local_search.hpp",
                "sequencing.hpp",
                "read_args.hpp",
                "common.hpp",
        ],
        deps = [
                "@optimizationtools//optimizationtools:info",
                "@optimizationtools//optimizationtools:utils",
        ],
        visibility = ["//visibility:public"],
)
